version: '3.8'

services:
  sean-gpt:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "backend/health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s